import csv

new_rows = [
    {
        "date_ajout": "2026-08-09",
        "statut": "NOUVEAU",
        "titre": "Très beau 7 1/2 (2 chambres + bureau), balcons refaits - Hochelaga-Maisonneuve",
        "quartier": "Hochelaga-Maisonneuve",
        "adresse": "n/d (secteur Hochelaga-Maisonneuve, Montréal, H1V 2R6)",
        "prix": "2200",
        "superficie_pi2": "1200",
        "chambres": "2",
        "balcon": "oui",
        "station_metro": "Pie-IX (estimé)",
        "ligne_metro": "verte",
        "minutes_a_pied": "10 (estimé)",
        "site": "Kijiji",
        "lien": "https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/tres-beau-7-1-2-a-louer-hochelaga-maisonneuve/1741046490",
        "score": "9",
        "notes": "2e étage d'un triplex, rénovation complète, électroménagers neufs, laveuse-sécheuse et lave-vaisselle intégrés, balcons refaits en 2022, proche du Stade olympique, eau incluse, bail 1 an, animaux limités, disponible 1er sept. 2026. Station métro estimée à partir du code postal et de la mention du Stade olympique (non confirmée).",
        "photo": "",
    },
    {
        "date_ajout": "2026-08-09",
        "statut": "NOUVEAU",
        "titre": "Grand 3 chambres (6 1/2), 1500 pi² - rue D'Iberville, à 2 min du métro D'Iberville",
        "quartier": "Villeray",
        "adresse": "7243, Rue D'Iberville, Montréal",
        "prix": "2200",
        "superficie_pi2": "1500",
        "chambres": "3",
        "balcon": "n/d",
        "station_metro": "D'Iberville",
        "ligne_metro": "bleue",
        "minutes_a_pied": "2",
        "site": "Centris",
        "lien": "https://www.centris.ca/fr/condo-appartement~a-louer~montreal-villeray-saint-michel-parc-extension/20850170",
        "score": "7",
        "notes": "6.5 pieces, 1 salle de bain, laveuse-secheuse dans la salle de bain, 2e etage, 1 stationnement (allee), disponible immediatement, locataire paie chauffage et electricite",
        "photo": "",
    },
    {
        "date_ajout": "2026-08-09",
        "statut": "NOUVEAU",
        "titre": "Charmant 6 1/2 rénové (3 chambres), 1100 pi², garage - Rosemont, à 11 min du métro Beaubien",
        "quartier": "Rosemont-La Petite-Patrie",
        "adresse": "5416, 14e Avenue, app. 1, Montréal",
        "prix": "2100",
        "superficie_pi2": "1100",
        "chambres": "3",
        "balcon": "n/d",
        "station_metro": "Beaubien",
        "ligne_metro": "orange",
        "minutes_a_pied": "11",
        "site": "Centris",
        "lien": "https://www.centris.ca/fr/condo-appartement~a-louer~montreal-rosemont-la-petite-patrie/15683980",
        "score": "7",
        "notes": "Rez-de-jardin, 2 salles de bain, garage, stationnement exterieur, solarium, cour arriere privee, atelier au sous-sol, disponible 16 aout 2026",
        "photo": "https://mspublic.centris.ca/media.ashx?id=ADDD250DA4EE48BDDDDDDDDDDB&t=pi&w=640&h=480&sm=c",
    },
    {
        "date_ajout": "2026-08-09",
        "statut": "NOUVEAU",
        "titre": "Cession de bail - Spacieux 3 chambres - 113 avenue Laurier Est (Plateau), à 7 min du métro Laurier",
        "quartier": "Le Plateau-Mont-Royal",
        "adresse": "113, Avenue Laurier Est, Montréal",
        "prix": "2275",
        "superficie_pi2": "n/d",
        "chambres": "3",
        "balcon": "n/d",
        "station_metro": "Laurier",
        "ligne_metro": "orange",
        "minutes_a_pied": "7",
        "site": "Marketplace",
        "lien": "https://www.facebook.com/marketplace/item/1334820052136089",
        "score": "4",
        "notes": "Climatisation incluse, frigo et cuisiniere inclus, chats acceptes, disponible maintenant, promotion en cours. Lien Facebook (connexion requise) pour plus de details",
        "photo": "https://scontent-yyz1-1.xx.fbcdn.net/v/t39.84726-6/756222412_1017386767836725_5739541558876083891_n.jpg?stp=c135.0.540.540a_dst-jpg_p180x540_tt6&_nc_cat=108&ccb=1-7&_nc_sid=92e707&_nc_ohc=1k4qbrVFJKQQ7kNvwEj3yoN&_nc_oc=AdpZYMJs7KK_vqKo_VnUSsID23B9yvH_t4K83jTVnEv2yoUM-9bYw0EumtA8a9aBZU8&_nc_zt=14&_nc_ht=scontent-yyz1-1.xx&_nc_gid=scQ6-RimtwNLLPrNy_sIVQ&_nc_ss=7f2a8&oh=00_AQGT30nwKt0hgdXqXg5fPPqpy_Q8L3RL9rOuQbnnpdioVg&oe=6A7E5515",
    },
    {
        "date_ajout": "2026-08-09",
        "statut": "NOUVEAU",
        "titre": "2 chambres, immeuble de 1910 - rue Clark (Plateau), à 11 min du métro Mont-Royal",
        "quartier": "Le Plateau-Mont-Royal",
        "adresse": "5738, Rue Clark, Montréal",
        "prix": "2300",
        "superficie_pi2": "n/d",
        "chambres": "2",
        "balcon": "n/d",
        "station_metro": "Mont-Royal",
        "ligne_metro": "orange",
        "minutes_a_pied": "11 (estimé)",
        "site": "Centris",
        "lien": "https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/14684301",
        "score": "3",
        "notes": "2e etage, immeuble de 1910, lumineux et bien entretenu, proche du Mile End et des rues Saint-Laurent/Saint-Viateur, disponible 1er juillet 2026, Walk Score 98",
        "photo": "",
    },
    {
        "date_ajout": "2026-08-09",
        "statut": "NOUVEAU",
        "titre": "5 1/2 (2 chambres) avec bureau, 2e étage - rue Saint-Viateur Ouest (Mile-End/Plateau)",
        "quartier": "Le Plateau-Mont-Royal",
        "adresse": "229, Rue Saint-Viateur Ouest, app. 3, Montréal",
        "prix": "2200",
        "superficie_pi2": "n/d",
        "chambres": "2",
        "balcon": "n/d",
        "station_metro": "Rosemont (estimé)",
        "ligne_metro": "orange",
        "minutes_a_pied": "12 (estimé)",
        "site": "Centris",
        "lien": "https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/12176453",
        "score": "3",
        "notes": "Salle a manger, bureau, semi-meuble (frigo et cuisiniere inclus), locataire paie chauffage et electricite, animaux et fumeurs non acceptes, disponible 5 jours apres acceptation, secteur Mile-End/Plateau, Walk Score 100",
        "photo": "",
    },
]

with open("annonces.csv", newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    existing = list(reader)

with open("annonces.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=fieldnames)
    w.writeheader()
    w.writerows(existing)
    w.writerows(new_rows)

print("added", len(new_rows), "total rows now", len(existing) + len(new_rows))
