import csv

path = 'annonces.csv'
with open(path, newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    rows = list(reader)

for r in rows:
    if r['statut'] == 'NOUVEAU':
        r['statut'] = 'vu'

D = '2026-07-23'

new_rows = [
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': 'Grand 5 1/2 rénové, 3 chambres - rue de Bellechasse (Rosemont, promo 1 mois gratuit)',
 'quartier': 'Rosemont-La Petite-Patrie', 'adresse': '4224, Rue de Bellechasse, Montréal',
 'prix': '2017', 'superficie_pi2': '1000', 'chambres': '3', 'balcon': 'oui',
 'station_metro': 'Rosemont', 'ligne_metro': 'verte', 'minutes_a_pied': '9',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/grand-5-1-2-4224-rue-de-bellechasse-rosemont-promo/1739379520',
 'score': '9',
 'notes': "Promo 1 mois gratuit sur bail 12 mois (prix régulier 2200$), chauffage/hydro/eau inclus, animaux acceptés, stationnement et casier inclus, balcons avant et arrière, disponible 1er juillet 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': 'Magnifique 5 1/2, 3 chambres + boudoir - rue Marie-Anne (Plateau), près métro Mont-Royal',
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': 'Rue Marie-Anne (H2H 1M9), Montréal',
 'prix': '2300', 'superficie_pi2': '1000', 'chambres': '3', 'balcon': 'oui',
 'station_metro': 'Mont-Royal', 'ligne_metro': 'verte', 'minutes_a_pied': '4-7',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/magnifique-5-1-2-sur-le-plateau-mont-royal/1734803750',
 'score': '9',
 'notes': "Meublé, planchers de bois franc et poutres apparentes, balcon privé, chauffage/électricité non inclus, option mois par mois, disponible 1er avril 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': 'Grand 5 1/2 lumineux, 2 chambres - Plateau-Mont-Royal, à 3 min du métro Laurier',
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': 'H2J 2Y3, Montréal',
 'prix': '2000', 'superficie_pi2': '1100', 'chambres': '2', 'balcon': 'oui',
 'station_metro': 'Laurier', 'ligne_metro': 'verte', 'minutes_a_pied': '3',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/grand-51-2-lumineux-sur-plateau-mont-royal/1738318103',
 'score': '9',
 'notes': "Chauffage inclus, petit balcon côté cuisine, animaux limités, disponible 1er juillet 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': 'Grand 5 1/2 avec balcon, 3 chambres - coin Chabot et L.-O.-David (Villeray), près métro Fabre',
 'quartier': 'Villeray', 'adresse': 'Coin Chabot et L.-O.-David (H2E 2V2), Montréal',
 'prix': '2000', 'superficie_pi2': '1140', 'chambres': '3', 'balcon': 'oui',
 'station_metro': 'Fabre', 'ligne_metro': 'bleue', 'minutes_a_pied': '3',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/grand-5-1-2-coin-chabot-et-l-o-davis/1740786014',
 'score': '9',
 'notes': "Meublé, stationnement inclus, aucun animal, disponible 1er août 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': 'Grand 5 1/2, 3 chambres - avenue St-Germain (Hochelaga), à 10 min du métro Préfontaine',
 'quartier': 'Hochelaga-Maisonneuve', 'adresse': '1921 Rue St-Germain, Montréal (H1W 2T5)',
 'prix': '2395', 'superficie_pi2': '950', 'chambres': '3', 'balcon': 'oui',
 'station_metro': 'Préfontaine', 'ligne_metro': 'verte', 'minutes_a_pied': '10',
 'site': 'Zumper', 'lien': 'https://www.zumper.com/listings/20844079p/3-bedroom-hochelaga-montreal-qc',
 'score': '9',
 'notes': "Entièrement rénové, concept ouvert, climatisation, laveuse-sécheuse et lave-vaisselle inclus, grand balcon arrière, animaux acceptés, hydro en sus, disponible 1er oct. 2026 ; attention, la page affichait aussi 2495$ ailleurs sur l'annonce, à valider avant de contacter",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': 'Grand 6 1/2, 3 chambres avec cour - Parc-Jarry (Villeray), à 4 min du métro Jarry',
 'quartier': 'Villeray', 'adresse': 'Secteur Parc-Jarry (H2R 2E9), Montréal',
 'prix': '1960', 'superficie_pi2': '1200', 'chambres': '3', 'balcon': 'oui',
 'station_metro': 'Jarry', 'ligne_metro': 'orange', 'minutes_a_pied': '4',
 'site': 'Zumper', 'lien': 'https://www.zumper.com/apartments-for-rent/14724140p/3-bedroom-parc-jarry-montreal-qc',
 'score': '9',
 'notes': "Immeuble restauré de 1924, planchers de bois franc, plafonds 9 pieds, balcons avant et arrière, chats seulement, disponible août/sept. 2026 ; la page affichait des mentions de bail datées 2018-2019, à vérifier auprès du proprio avant de contacter",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': 'Grand 4½ neuf, 2 chambres + boudoir fermé - avenue Gascon (Centre-Sud), à 7 min du métro Préfontaine',
 'quartier': 'Ville-Marie (Centre-Sud)', 'adresse': 'Avenue Gascon, Montréal',
 'prix': '2175', 'superficie_pi2': '900', 'chambres': '2', 'balcon': 'oui',
 'station_metro': 'Frontenac ou Préfontaine', 'ligne_metro': 'verte', 'minutes_a_pied': '7',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/grand-4-neuf-dernier-etage-vue-plateau-ville-marie/1739397387',
 'score': '8',
 'notes': "Dernier étage rénové avec vue, 2 chambres fermées + boudoir fermé pouvant servir de 3e chambre, 2 balcons, eau et internet inclus, chats acceptés, disponible 1er juillet 2026, secteur près du parc Baldwin",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': 'Grand 5 1/2 (1200 pi²), 3 chambres au rez-de-chaussée - avenue Charlemagne (Rosemont), près métro Pie-IX',
 'quartier': 'Rosemont-La Petite-Patrie', 'adresse': '4419, Avenue Charlemagne, Montréal (H1X 2H2)',
 'prix': '1900', 'superficie_pi2': '1200', 'chambres': '3', 'balcon': 'n/d',
 'station_metro': 'Pie-IX', 'ligne_metro': 'verte', 'minutes_a_pied': '7',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/grand-5-1-2-renove-a-louer-au-rdc-a-rosemont/1740506864',
 'score': '8',
 'notes': "Rez-de-chaussée rénové, climatisation incluse, aucun animal, disponible 1er juillet 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': '2 chambres avec balcon, 1000 pi² - rue William-Tremblay (Hochelaga), à 10 min du métro Joliette',
 'quartier': 'Hochelaga-Maisonneuve', 'adresse': '3439 Rue William-Tremblay, Montréal',
 'prix': '2050', 'superficie_pi2': '1000', 'chambres': '2', 'balcon': 'oui',
 'station_metro': 'Joliette', 'ligne_metro': 'verte', 'minutes_a_pied': '10',
 'site': 'LogisQuébec', 'lien': 'https://www.logisquebec.com/condo-a-louer-rosemont_la-petite-patrie-l353563',
 'score': '8',
 'notes': "Condo entièrement meublé, 2e étage coin avec vue sur parc, électroménagers inclus, accès gym, non-fumeur, électricité et internet en sus (~70$ chacun), disponible 1er août ou 1er sept. 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': '5½ (semi-meublé), 2 chambres + bureau - rue St-Denis (Villeray), à 6 min du métro Jarry',
 'quartier': 'Villeray', 'adresse': '8360, Rue St-Denis, Montréal',
 'prix': '2200', 'superficie_pi2': '1100', 'chambres': '2', 'balcon': 'oui',
 'station_metro': 'Jarry', 'ligne_metro': 'orange', 'minutes_a_pied': '6',
 'site': 'DuProprio', 'lien': 'https://duproprio.com/fr/location/montreal/villeray-st-michel-parc-extension/5-1-2-a-louer/hab-8360-st-denis-1132893',
 'score': '8',
 'notes': "2e étage d'un plex centenaire entièrement rénové, balcon arrière sur ruelle tranquille, 1 stationnement extérieur inclus, disponible 1er sept. 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "Grand 5 1/2, 3 chambres fermées - boulevard Rosemont, à 2 min du métro Rosemont",
 'quartier': 'Rosemont-La Petite-Patrie', 'adresse': 'Boulevard Rosemont (H1Y 1M5), Montréal',
 'prix': '2215', 'superficie_pi2': '1000', 'chambres': '3', 'balcon': 'n/d',
 'station_metro': 'Rosemont', 'ligne_metro': 'verte', 'minutes_a_pied': '2',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/appartement-5-1-2-rosemont-la-petite-patrie/1740125612',
 'score': '7',
 'notes': "Cour intérieure privée exclusive, climatisation incluse, chiens acceptés, disponible 1er août 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': '2 chambres avec balcon, immeuble rénové - rue Iberville (Villeray/Parc-Ex), à 1 min du métro d\'Iberville',
 'quartier': 'Villeray', 'adresse': '7186, Rue Iberville, Montréal',
 'prix': '1975', 'superficie_pi2': '900', 'chambres': '2', 'balcon': 'oui',
 'station_metro': "D'Iberville", 'ligne_metro': 'bleue', 'minutes_a_pied': '1',
 'site': 'DuProprio', 'lien': 'https://duproprio.com/fr/location/montreal/villeray-st-michel-parc-extension/5-1-2-a-louer/hab-7186-iberville-1132385',
 'score': '7',
 'notes': "Entièrement rénové (2024), plancher chauffant salle de bain, grand balcon arrière couvert, aucun animal, Walk Score 94, disponible 1er juillet 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "Cession de bail 6 1/2 rénové, 4 chambres (1000 pi²) - rue Leclaire (Hochelaga), près métro Joliette",
 'quartier': 'Hochelaga-Maisonneuve', 'adresse': 'Rue Leclaire (H1V 2H6), Montréal',
 'prix': '2020', 'superficie_pi2': '1000', 'chambres': '4', 'balcon': 'n/d',
 'station_metro': 'Joliette', 'ligne_metro': 'verte', 'minutes_a_pied': '3-5',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/6-1-2-renove-rue-leclaire-hochelaga-maisonneuve/1739743063',
 'score': '7',
 'notes': "Cession de bail, rez-de-chaussée, cour privée, chauffage électrique inclus, aucun animal, disponible 1er août 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "5 1/2 haut de gamme rénové, 2 chambres - à 1 min du métro Iberville (Villeray)",
 'quartier': 'Villeray', 'adresse': 'Secteur métro Iberville (H1X), Montréal',
 'prix': '1915', 'superficie_pi2': '950', 'chambres': '2', 'balcon': 'oui',
 'station_metro': "D'Iberville", 'ligne_metro': 'orange', 'minutes_a_pied': '1',
 'site': 'Kijiji', 'lien': 'https://www.kijiji.ca/v-apartments-condos/ville-de-montreal/5-haut-de-gamme-renove-a-2-pas-du-metro-iberville/1740921727',
 'score': '7',
 'notes': "Entièrement rénové (printemps 2024), plancher chauffant salle de bain, grand balcon arrière couvert, aucun animal, disponible 1er juillet 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "3 chambres, 1011 pi² - rue Saint-Gérard (Villeray), entre métro Jarry et De Castelnau",
 'quartier': 'Villeray', 'adresse': '7442, Rue Saint-Gérard, Montréal',
 'prix': '2300', 'superficie_pi2': '1011', 'chambres': '3', 'balcon': 'n/d',
 'station_metro': 'Jarry ou De Castelnau', 'ligne_metro': 'orange/bleue', 'minutes_a_pied': '8-11',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-villeray-saint-michel-parc-extension/25184748',
 'score': '6',
 'notes': "Thermopompe murale, 2 salles de bain, 2 stationnements disponibles (150$/mois chacun), Walk Score 99",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "6857 rue Marquette, 3 chambres avec balcon - Rosemont, à 6 min du métro Fabre",
 'quartier': 'Rosemont-La Petite-Patrie', 'adresse': '6857, Rue Marquette, app. 3, Montréal',
 'prix': '2200', 'superficie_pi2': 'n/d', 'chambres': '3', 'balcon': 'oui',
 'station_metro': 'Fabre', 'ligne_metro': 'bleue', 'minutes_a_pied': '6',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-rosemont-la-petite-patrie/28846310',
 'score': '6',
 'notes': "5½ entièrement rénové, balcons avant et arrière, animaux non acceptés, Walk Score 94, disponible 7 jours après acceptation",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "6 pièces, 3 chambres - rue Cartier (Villeray), à quelques minutes du métro Fabre",
 'quartier': 'Villeray', 'adresse': '7556, Rue Cartier, Montréal',
 'prix': '1950', 'superficie_pi2': 'n/d', 'chambres': '3', 'balcon': 'n/d',
 'station_metro': 'Fabre', 'ligne_metro': 'bleue', 'minutes_a_pied': '3-5 (estimé)',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-villeray-saint-michel-parc-extension/26990180',
 'score': '4',
 'notes': "Récemment rénové, animaux non acceptés, preuve de revenu exigée, Walk Score 94",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "3 chambres (950 pi²), balcon - rue St-Viateur Est (Mile-End/Rosemont), à 9 min du métro Rosemont",
 'quartier': 'Rosemont-La Petite-Patrie', 'adresse': '81, Rue Saint-Viateur Est, Montréal',
 'prix': '2050', 'superficie_pi2': '1100', 'chambres': '3', 'balcon': 'n/d',
 'station_metro': 'Rosemont', 'ligne_metro': 'orange', 'minutes_a_pied': '9',
 'site': 'Zumper', 'lien': 'https://www.zumper.com/address/81-rue-saint-viateur-e-montreal-qc-h2t-1a7-can',
 'score': '7',
 'notes': "Unité de coin entièrement rénovée, comptoirs de quartz, planchers de terrazzo/parquet restaurés, chaque chambre a son placard, animaux acceptés",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "3 chambres, 2339$ avec balcon - rue Rachel Est (Plateau), à 10 min du métro Mont-Royal",
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': '1101, Rue Rachel Est, app. 207, Montréal',
 'prix': '2339', 'superficie_pi2': 'n/d', 'chambres': '2', 'balcon': 'oui',
 'station_metro': 'Mont-Royal', 'ligne_metro': 'verte', 'minutes_a_pied': '10',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/14671081',
 'score': '6',
 'notes': "1 mois gratuit en promotion, piscine intérieure chauffée, terrasse sur le toit, gym, sauna, animaux acceptés, stationnement garage 220$/mois, Walk Score 98",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "3 chambres avec grand balcon arrière - rue Marie-Anne Est (Plateau), à 5-6 min du métro Mont-Royal",
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': '2171, Rue Marie-Anne Est, Montréal',
 'prix': '2300', 'superficie_pi2': 'n/d', 'chambres': '3', 'balcon': 'oui',
 'station_metro': 'Mont-Royal ou Papineau', 'ligne_metro': 'verte', 'minutes_a_pied': '5-6',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/13403770',
 'score': '7',
 'notes': "Triplex 1949 rénové, planchers de bois franc, chats et petits chiens acceptés sous conditions, Walk Score 99",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "3 chambres (1165 pi²) - avenue du Parc (secteur Mile-End nord), à 11 min du métro Outremont",
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': '5956, Avenue du Parc, app. 2, Montréal',
 'prix': '2395', 'superficie_pi2': '1165', 'chambres': '3', 'balcon': 'n/d',
 'station_metro': 'Outremont', 'ligne_metro': 'bleue', 'minutes_a_pied': '11',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/28120701',
 'score': '7',
 'notes': "Murs de pierre, planchers d'érable, disponible 1er juin 2026, Walk Score 98, stationnement optionnel 125$/mois, secteur nord de l'avenue du Parc (limite Mile-End/Parc-Extension)",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "3 chambres avec terrasse sur cour intérieure - rue De Bullion (Plateau), à 9 min du métro Saint-Laurent",
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': '3560, Rue De Bullion, Montréal',
 'prix': '2400', 'superficie_pi2': 'n/d', 'chambres': '3', 'balcon': 'oui',
 'station_metro': 'Saint-Laurent', 'ligne_metro': 'verte', 'minutes_a_pied': '9',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/15238222',
 'score': '7',
 'notes': "Meublé, chauffage/internet/électricité inclus, secteur Prince-Arthur/Saint-Denis, immeuble de 1845, Walk Score 100",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "2 chambres, 930 pi² avec balcon privé meublé - rue Saint-Dominique (Villeray), à 8 min du métro Jarry",
 'quartier': 'Villeray', 'adresse': '8478, Rue Saint-Dominique, Montréal',
 'prix': '2290', 'superficie_pi2': '930', 'chambres': '2', 'balcon': 'oui',
 'station_metro': 'Jarry', 'ligne_metro': 'orange', 'minutes_a_pied': '8',
 'site': 'DuProprio', 'lien': 'https://duproprio.com/fr/location/montreal/villeray-st-michel-parc-extension/4-1-2-a-louer/hab-8478-saint-dominique-1134387',
 'score': '7',
 'notes': "Condo entièrement meublé, 1 stationnement intérieur, thermopompe murale (chauffage inclus), animaux négociables, bail minimum 12 mois, disponible 1er juillet 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "2 chambres avec balcons avant/arrière - rue Chambord (Villeray), à 5 min du métro Fabre",
 'quartier': 'Villeray', 'adresse': '7572, Rue Chambord, Montréal',
 'prix': '1980', 'superficie_pi2': '940', 'chambres': '2', 'balcon': 'oui',
 'station_metro': 'Fabre', 'ligne_metro': 'bleue', 'minutes_a_pied': '5',
 'site': 'DuProprio', 'lien': 'https://duproprio.com/fr/location/montreal/villeray-st-michel-parc-extension/5-1-2-a-louer/hab-7572-chambord-1133371',
 'score': '7',
 'notes': "Semi-meublé, non-fumeur, animaux non acceptés, proche parc Villeray (2 min) et marché Jean-Talon (15 min), 1 mois gratuit sur renouvellement, disponible 1er août 2026",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "2 chambres, 950 pi² au rez-de-chaussée - rue Jarry Est (Villeray), à 1-2 coins de rue du métro Jarry",
 'quartier': 'Villeray', 'adresse': '659, Rue Jarry Est, app. 4, Montréal',
 'prix': '2000', 'superficie_pi2': '950', 'chambres': '2', 'balcon': 'n/d',
 'station_metro': 'Jarry', 'ligne_metro': 'orange', 'minutes_a_pied': '2 (estimé)',
 'site': 'Zumper', 'lien': 'https://www.zumper.com/apartment-buildings/p1626378/659-rue-jarry-e-parc-jarry-montreal-qc',
 'score': '5',
 'notes': "Entièrement rénové, nouveaux électroménagers, chauffage au gaz, climatiseur mural, laveuse-sécheuse dans l'unité, animaux acceptés, hydro en sus",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "2 chambres, 925 pi² - avenue d'Outremont (Villeray), à 3-4 min du métro Acadie",
 'quartier': 'Villeray', 'adresse': "6900, Avenue d'Outremont, app. 307, Montréal",
 'prix': '2200', 'superficie_pi2': '925', 'chambres': '2', 'balcon': 'n/d',
 'station_metro': 'Acadie', 'ligne_metro': 'bleue', 'minutes_a_pied': '3-4',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-villeray-saint-michel-parc-extension/10336702',
 'score': '5',
 'notes': "Stationnement intérieur inclus, immeuble neuf (2019), secteur en développement près du campus MIL de l'Université de Montréal, Walk Score 98",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "2 chambres, 954 pi² - rue Guizot Ouest (Villeray), près du parc Jarry",
 'quartier': 'Villeray', 'adresse': '5, Rue Guizot Ouest, app. 202, Montréal',
 'prix': '2335', 'superficie_pi2': '954', 'chambres': '2', 'balcon': 'n/d',
 'station_metro': 'Jarry', 'ligne_metro': 'orange', 'minutes_a_pied': '8-10 (estimé)',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-villeray-saint-michel-parc-extension/13280662',
 'score': '5',
 'notes': "Eau chaude et internet inclus, immeuble neuf (2022), adjacent au parc Jarry, Walk Score 95",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "2 chambres - rue De Lanaudière (Rosemont), à 6 min du métro Jean-Talon",
 'quartier': 'Rosemont-La Petite-Patrie', 'adresse': '6583, Rue De Lanaudière, Montréal',
 'prix': '1945', 'superficie_pi2': 'n/d', 'chambres': '2', 'balcon': 'n/d',
 'station_metro': 'Jean-Talon', 'ligne_metro': 'orange/bleue', 'minutes_a_pied': '6',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-rosemont-la-petite-patrie/20257676',
 'score': '3',
 'notes': "Chauffage central inclus + 5 électroménagers, quintuplex de 1932, disponible 1er sept. 2026, Walk Score 94",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "3 chambres - rue Saint-Dominique (Plateau), à 8 min du métro Sherbrooke/Saint-Laurent",
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': '3554, Rue Saint-Dominique, Montréal',
 'prix': '2300', 'superficie_pi2': 'n/d', 'chambres': '3', 'balcon': 'n/d',
 'station_metro': 'Sherbrooke ou Saint-Laurent', 'ligne_metro': 'orange', 'minutes_a_pied': '8 (estimé)',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/17619217',
 'score': '4',
 'notes': "Immeuble construit en 1915, stationnement ruelle 200$/mois en sus, disponible 7 jours après acceptation, Walk Score 100",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "2 chambres avec cour privée - rue Demers (Plateau), près du métro Laurier",
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': '170, Rue Demers, Montréal',
 'prix': '2350', 'superficie_pi2': 'n/d', 'chambres': '2', 'balcon': 'non',
 'station_metro': 'Laurier', 'ligne_metro': 'orange', 'minutes_a_pied': '8-10 (estimé)',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/15892581',
 'score': '3',
 'notes': "Thermopompe murale incluse, meublé, cour privée (pas de balcon), animaux non acceptés, secteur Mile End, Walk Score 99",
 'photo': ''},
{'date_ajout': D, 'statut': 'NOUVEAU',
 'titre': "2 chambres, rez-de-chaussée avec cour partagée - rue De Bullion (Plateau/Mile-End), à 5 min du métro Mont-Royal",
 'quartier': 'Le Plateau-Mont-Royal', 'adresse': '4632, Rue De Bullion, Montréal',
 'prix': '2095', 'superficie_pi2': 'n/d', 'chambres': '2', 'balcon': 'non',
 'station_metro': 'Mont-Royal', 'ligne_metro': 'verte', 'minutes_a_pied': '5',
 'site': 'Centris', 'lien': 'https://www.centris.ca/fr/condo-appartement~a-louer~montreal-le-plateau-mont-royal/16426752',
 'score': '4',
 'notes': "Semi-meublé, cour partagée (pas de balcon), animaux acceptés sous conditions, disponible 1er sept. 2026, Walk Score 100",
 'photo': ''},
]

existing_links = {r['lien'] for r in rows}
added = 0
for nr in new_rows:
    if nr['lien'] not in existing_links:
        rows.append(nr)
        added += 1
    else:
        print("SKIP dup", nr['lien'])

def sort_key(r):
    is_new = 0 if r['statut'] == 'NOUVEAU' else 1
    try:
        score = -int(r['score'])
    except:
        score = 0
    return (is_new, score)

rows.sort(key=sort_key)

with open(path, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Added {added} new rows. Total rows now: {len(rows)}")
